os: linux

dist: bionic

language: php

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.4

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

after_success:
  - |
    if [[ $TRAVIS_PHP_VERSION == "7.4" ]]; then
      bash <(curl -s https://codecov.io/bash);
      travis_retry php vendor/bin/php-coveralls --coverage_clover=./logs/tests/clover.xml --json_path=./logs/tests/coveralls-upload.json -v;
    fi